### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by kevintransp** [BTNGaming/gcphone_esxfix#8]
Good day,
I hope you can help me out. When we recieved a new message and open the message app a white screen appairs. After reconnect i can open the app without any problems.

In the F8 menu i see this:

nui://gcpphone/html/static/js/vendor.js:1074, type error: cannot read property "0" of undefined.

**Comment by BTNGaming** [comment]
Make sure you have mysql-async 2.1.1 or 2.x.x but NOT 3.x, ALSO Make sure your other scripts in the REQUIREMENTS tab are the proper versions. That has been the biggest issue most people have. otherwhise reinstall the ADDONS phone and the phone itself again and see what happens. It's working on my server and the version I am running is the exact same, with a few addons in the home screen.

**Comment by kevintransp** [comment]
Thanks i will try that. Indeed i upgrade async.

**Comment by kevintransp** [comment]
To bad, changing back to the earlier version of async doesnt solve the problem.  Other suggestions?

Kind regarts.

**Comment by BTNGaming** [comment]
After running several tests, We found that anyone with this issue is running async 3.x.x instead of 2.x.x and the phone was never updated to the newest version of Async. I will update it as soon I can but currently with my server running 2 separate FULL servers, my time has been consumed and It will stay that way for awhile as this will be my back burner project.
